# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: daily photo

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 9 * * *'
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'
    - name: Install Dependence
      run: pip install requests
    - name: Run
      run: python dailyphoto.py
    - name: Commit files
      uses: EndBug/add-and-commit@v7
      with:
        default_author: github_actions
#      run: |
#         git config --local user.email "2247868358@qq.com"
#         git config --local user.name "lustime"
#         git add *.md
#         git commit -m "update readme.md"
    - name: Push changes
      uses:  ad-m/github-push-action@master
      with:
         github_token: ${{ secrets.MY_GIT_TOKEN }}
         branch: main
    - name: Checkout download branch
      uses: actions/checkout@v2
      with:
         ref: upload # Change to your branch to place crawled pictures
    - name: Run downloaddailypic.py
      run: python downloaddailypic.py
    - name: list
      run: git status
    - name: Commit files
      uses: EndBug/add-and-commit@v7
      with:
        default_author: github_actions
#      run: |
#          git config --local user.email "2247868358@qq.com"
#          git config --local user.name "lustime"
#          git add "*.jpg"
#          git commit -m "upload pic"
    - name: Push changes
      uses:  ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.MY_GIT_TOKEN }}
        branch: upload
